use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Leon0206/MDSpecs.git'
platform :ios, '9.0'

target 'MDUIMaterialKit_Example' do
  pod 'MDUIMaterialKit', :path => '../'
  pod 'MDCommonKit', '~> 1.0.0'
  pod 'EasyLayout', '~> 1.0.0'
end
